# Generated by Django 5.0.6 on 2024-05-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('abbr_name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(max_length=300, upload_to='university_images/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=800)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.region')),
            ],
            options={
                'verbose_name': 'Tuman (Shahar)',
                'verbose_name_plural': 'Tuman (Shahar)lar',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=400)),
                ('study_code', models.CharField(max_length=15)),
                ('science_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_1', to='exam.science')),
                ('science_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_2', to='exam.science')),
            ],
        ),
        migrations.CreateModel(
            name='StudyInUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_ball', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('contract_ball', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('grant_count', models.IntegerField(blank=True, default=0)),
                ('contract_count', models.IntegerField(blank=True, default=0)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.study')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.university')),
            ],
        ),
    ]
